<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'App__Entity__CurrencyRateHistory__CLASSMETADATA__' => 0,
'App__Entity__Currency__CLASSMETADATA__' => 1,

], [

0 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping')),
        clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
        clone ($p['Symfony\\Bridge\\Doctrine\\IdGenerator\\UuidGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Bridge\\Doctrine\\IdGenerator\\UuidGenerator')),
        clone ($p['Symfony\\Component\\Uid\\Factory\\UuidFactory'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Uid\\Factory\\UuidFactory')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\CurrencyRateHistory',
            ],
            'customGeneratorDefinition' => [
                [
                    'class' => 'Symfony\\Bridge\\Doctrine\\IdGenerator\\UuidGenerator',
                ],
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\CurrencyRateHistoryRepository',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'generatorType' => [
                7,
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                    'rate' => $o[2],
                    'date' => $o[3],
                ],
            ],
            'fieldNames' => [
                [
                    'id' => 'id',
                    'rate' => 'rate',
                    'date' => 'date',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id',
                    'rate' => 'rate',
                    'date' => 'date',
                ],
            ],
            'table' => [
                [
                    'name' => 'currency_rate_history',
                ],
            ],
            'associationMappings' => [
                [
                    'currency' => $o[4],
                ],
            ],
            'idGenerator' => [
                $o[6],
            ],
            'cache' => [
                [
                    'region' => 'app_entity_currencyratehistory',
                    'usage' => 1,
                ],
            ],
            'name' => [
                'App\\Entity\\CurrencyRateHistory',
                5 => 'currency_id',
            ],
            'id' => [
                1 => true,
            ],
            'unique' => [
                1 => true,
                5 => false,
            ],
            'type' => [
                1 => 'uuid',
                'float',
                'datetime',
            ],
            'fieldName' => [
                1 => 'id',
                'rate',
                'date',
            ],
            'columnName' => [
                1 => 'id',
                'rate',
                'date',
            ],
            'fetch' => [
                4 => 2,
            ],
            'sourceEntity' => [
                4 => 'App\\Entity\\CurrencyRateHistory',
            ],
            'inversedBy' => [
                4 => 'history',
            ],
            'sourceToTargetKeyColumns' => [
                4 => [
                    'currency_id' => 'iso3',
                ],
            ],
            'targetToSourceKeyColumns' => [
                4 => [
                    'iso3' => 'currency_id',
                ],
            ],
            'joinColumns' => [
                4 => [
                    $o[5],
                ],
            ],
            'joinColumnFieldNames' => [
                4 => [
                    'currency_id' => 'currency_id',
                ],
            ],
            'deferrable' => [
                5 => false,
            ],
            'nullable' => [
                5 => false,
            ],
            'referencedColumnName' => [
                5 => 'iso3',
            ],
        ],
        'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
            'fieldName' => [
                4 => 'currency',
            ],
            'targetEntity' => [
                4 => 'App\\Entity\\Currency',
            ],
        ],
        'Symfony\\Bridge\\Doctrine\\IdGenerator\\UuidGenerator' => [
            'protoFactory' => [
                6 => $o[7],
            ],
            'factory' => [
                6 => $o[7],
            ],
        ],
        'Symfony\\Component\\Uid\\Factory\\UuidFactory' => [
            'defaultClass' => [
                7 => 'Symfony\\Component\\Uid\\UuidV7',
            ],
            'timeBasedClass' => [
                7 => 'Symfony\\Component\\Uid\\UuidV7',
            ],
            'nameBasedClass' => [
                7 => 'Symfony\\Component\\Uid\\UuidV5',
            ],
            'randomBasedClass' => [
                7 => 'Symfony\\Component\\Uid\\UuidV4',
            ],
            'timeBasedNode' => [
                7 => null,
            ],
            'nameBasedNamespace' => [
                7 => null,
            ],
        ],
    ],
    $o[0],
    []
); } },
1 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping')),
        clone ($p['Doctrine\\ORM\\Id\\AssignedGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\AssignedGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\Currency',
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\CurrencyRepository',
            ],
            'identifier' => [
                [
                    'iso3',
                ],
            ],
            'fieldMappings' => [
                [
                    'iso3' => $o[1],
                    'rate' => $o[2],
                    'updatedAt' => $o[3],
                ],
            ],
            'fieldNames' => [
                [
                    'iso3' => 'iso3',
                    'rate' => 'rate',
                    'updated_at' => 'updatedAt',
                ],
            ],
            'columnNames' => [
                [
                    'iso3' => 'iso3',
                    'rate' => 'rate',
                    'updatedAt' => 'updated_at',
                ],
            ],
            'table' => [
                [
                    'name' => 'currency',
                ],
            ],
            'entityListeners' => [
                [
                    'preUpdate' => [
                        [
                            'class' => 'App\\EventListener\\CurrencyUpdateEventListener',
                            'method' => 'onUpdate',
                        ],
                    ],
                ],
            ],
            'associationMappings' => [
                [
                    'history' => $o[4],
                ],
            ],
            'idGenerator' => [
                $o[5],
            ],
            'cache' => [
                [
                    'region' => 'app_entity_currency',
                    'usage' => 1,
                ],
            ],
            'name' => [
                'App\\Entity\\Currency',
            ],
            'length' => [
                1 => 3,
            ],
            'id' => [
                1 => true,
            ],
            'unique' => [
                1 => true,
            ],
            'type' => [
                1 => 'string',
                'float',
                'datetime',
            ],
            'fieldName' => [
                1 => 'iso3',
                'rate',
                'updatedAt',
            ],
            'columnName' => [
                1 => 'iso3',
                'rate',
                'updated_at',
            ],
            'cascade' => [
                4 => [
                    'remove',
                    'persist',
                    'refresh',
                    'detach',
                ],
            ],
            'fetch' => [
                4 => 4,
            ],
            'sourceEntity' => [
                4 => 'App\\Entity\\Currency',
            ],
            'mappedBy' => [
                4 => 'currency',
            ],
            'orderBy' => [
                4 => [
                    'date' => 'DESC',
                ],
            ],
        ],
        'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
            'fieldName' => [
                4 => 'history',
            ],
            'targetEntity' => [
                4 => 'App\\Entity\\CurrencyRateHistory',
            ],
        ],
    ],
    $o[0],
    []
); } },

]];
