<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXmTngrY\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXmTngrY/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerXmTngrY.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerXmTngrY\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerXmTngrY\App_KernelProdContainer([
    'container.build_hash' => 'XmTngrY',
    'container.build_id' => 'f5c5f2dd',
    'container.build_time' => 1765898913,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXmTngrY');
